language: php

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

install: composer install --prefer-dist --no-interaction

script:
    - phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
